name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: 04-using-actions/react-app
    steps: 
        - name: Checkout code #want the workdlow to read code from the repo since react app is there
          uses: actions/checkout@v4
        # - name: Printing folders
        #   run: ls
        - name: Setup Node
          uses: actions/setup-node@v3
          with: 
            node-version: '20.x'
        - name: Install dependencies
          run: npm ci #cuz by default it is using root
        #   working-directory: 04-using-actions/react-app
        # - name: Run Unit test
        #   run: npm run test #predefined script in package.json
        #   working-directory: 04-using-actions/react-app