name: 11 - working with inputs
on: 
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                description: 'Skip deployment and only print build output'
                default: false
            target:
                type: environment #populated based on environments defined in ur repo!
                required: true
                description: 'Which environment the workflow will target'
            tag:
                description: 'Release from which to build and deploy'
                type: choice
                options:
                    - v1
                    - v2
                    - v3
                default: v3
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: |
                echo "Building from tag ${{inputs.tag}}"
    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{!inputs.dry-run}}
        environment: ${{inputs.target}}
        steps:
            - name: Deploy
              run: echo "Deploying to ${{inputs.target}}"
