name: '13 - Using Caching'
on:
    workflow_dispatch: 
        inputs:
            use-cache:
                description: checking if cache to be used or not
                type: boolean
                default: true
            node-version:
                description: Node version
                type: choice
                options:
                    - 18.x
                    - 20.x
                    - 21.x
                default: 20.x

jobs:
    install-deps:
        runs-on: ubuntu-latest
        outputs: 
            deps-cache-key:
                steps.cache-key.outputs.CACHE_KEY
                
        defaults:
            run:
                working-directory: 
                    13-caching/react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            - name: Setup Node
              uses: actions/setup-node@v6
              with: 
                node-version: '20.x'
                
            - name: Calculate Cache Key
              id: cache-key
              run: |
                echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" >> "$GITHUB_OUTPUT"
            #calculating cache key to be used in next step in current step
            - name: Dowload Cached Dependencies
              uses: actions/cache@v4
              if: ${{inputs.use-cache}}
              id: cache
              with:
                path: 13-caching/react-app/node_modules
                key: ${{steps.cache-key.outputs.CACHE_KEY}}
                #we use this synatx and not output name since its an output in another step but in same job!
            - name: Install dependencies #if cache miss install dependencies
              if: steps.cache.outputs.cache-hit!='true' 
              run: npm ci
    lint-test:
        runs-on: ubuntu-latest
        needs: install-deps
        defaults:
            run:
                working-directory: 13-caching/react-app
        steps:
            - name: Checkout code #this changes working directory to root
              uses: actions/checkout@v6

            - name: Setup Node
              uses: actions/setup-node@v6
              with: 
                node-version: ${{inputs.node-version}}
            - name: Download cached dependencies
              uses: actions/cache@v3
              if: ${{inputs.use-cache}}
              id: cache
              with:
               path: 13-caching/react-app/node_modules
               key: ${{needs.install-deps.outputs.deps-cache-key}}
            #speciifyng cache key so that unrelated file changes (other folders package-lock ile) dont affect the hash of current key 
            - name: Install dependencies
              if: steps.cache.outputs.cache-hit!='true' 
            #exposed by cache action by default
              run: npm ci
            - name: Testing
              run: npm run test
            - name: Linting
              run: echo "Linting..."
            # - name: Building
            #   run: npm run build
            # - name: Deploying to nonprod
            #   run: echo "Deploying to no prod"
    build:
        runs-on: ubuntu-latest
        needs: install-deps
        defaults:
            run:
                working-directory: 13-caching/react-app
        steps:
            - name: Checkout code #this changes working directory to root
              uses: actions/checkout@v6
            
            - name: Setup Node
              uses: actions/setup-node@v6
              with: 
                node-version: ${{inputs.node-version}}
            - name: Download cached dependencies
              uses: actions/cache@v3
              if: ${{inputs.use-cache}}
              id: cache
              with:
                path: 13-caching/react-app/node_modules
                key: ${{needs.install-deps.outputs.deps-cache-key}}
                #speciifyng cache key so that unrelted file changes (other folders package-lock ile) dont affect the hash of current key 
            - name: Install dependencies
              if: steps.cache.outputs.cache-hit!='true' 
            #exposed by cache action by default
              run: npm ci
            # - name: Testing
            #   run: npm run test
            - name: Building
              run: npm run build
            # - name: Deploying to nonprod
            #   run: echo "Deploying to no prod"
                                                                
                                                                
# the reason why we are again calling cache action in last 2 jobs is since on gitub hosted runners cache is not persisted between job. so we are resuing the key by outputting in previous job

#also note that here we are purely going by package-lock.json dependencies being contained in node_modules. there can be even others depending on the platform eg macos, windows..so it doesnt make sense to cache it like how we are doing here..should ideally inlcude runner.os as well in the key to avid sharing same cache across platforms