name: 14 - Working with Artifacts
on: 
    workflow_dispatch:
jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 14-artifacts/react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                node-version: 20.x
            - name: Download cached dependencies
              id: cache
              uses: actions/cache@v4
              with:
                    path: 14-artifacts/react-app/node_modules #It's important to provide the entire path, since the working-directory option set as default at the job level applies only to run commands.
                    key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}
            - name: install dependencies
              run: npm ci
            - name: Unit tests
              run: npm run test -- --coverage
            - name: Upload test results
              uses: actions/upload-artifact@v4
              with:
                name: test-coverage
                path: 14-artifacts/react-app/coverage
            - name: Build code
              run: npm run build
            - name: Upload build files
              uses: actions/upload-artifact@v4
              with:
                 name: app
                 path: 14-artifacts/react-app/build 

    deploy:
        runs-on: ubuntu-latest
        needs: test-build
        steps:
            - name: Upload test results
              uses: actions/download-artifact@v4
              with:
                name: test-coverage
                path: coverage
            - name: Download build files
              uses: actions/download-artifact@v5
              with:
                name: app
                path: build
                
            - name: Show folder structure
              run: ls -R
    
    